title: DocumentaÃ§Ã£o Meio
description: DocumentaÃ§Ã£o da Tecnologia do Meio
theme: just-the-docs

url: https://annecamille.github.io/

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
nav_enabled: true

callouts:
  warning:
    title: Warning
    color: red
  obs:
    title: ðŸ’¡ Dicas
    color: blue

